Set up associations
principlebrothers/School_Library_OOP pull request #3
Opened 2022-09-28 17:27 UTC by principlebrothers

## Complete milestone 3

### In this project, I finish creating the remaining classes for the school library and create the associations between them.
> The classes are 
- [x] classroom
- [x] rental and 
- [x] book

2022-09-28 19:28 UTC, medaminedev66 requested changes
Hi @principlebrothers  😃, :wave:, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- The repo looks professional.
- There are no linter errors.
- You have a descriptive PR.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-28 19:28 UTC, medaminedev66 commented on book.rb
> +  attr_reader :rentals
- [ ] According to the "a book has many rentals" relationship, setters for @rentals should be present in the Book class.

2022-09-28 19:28 UTC, medaminedev66 commented on book.rb
> +  end
- [ ] According to the `many-to-many` (also `has-many-through`) relationship between `Person` and `Book` using the intermediate class `Rental`:
  - A method for adding rentals should be present in the Book class. Check out the example in a previous lesson: [many-to-many-relationship](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/articles/oop_relationships_by_examples.md#many-to-many-relationship).

2022-09-28 19:28 UTC, medaminedev66 commented on rental.rb
> +  attr_accessor :date
- [ ] Because a rental belongs to a book and also belongs to a person, Getters and Setters for `@book` and `@person` instance variables should be present in the Rental class.

2022-09-28 19:28 UTC, medaminedev66 commented on person.rb
> +  attr_reader :id, :rentals
- [ ] According to  "a person has many rentals" relationship, Setters for @rentals should be present in the Person class.

2022-09-28 19:28 UTC, medaminedev66 commented on person.rb
>  end
- [ ] Accorsding to "a person has many rentals" relationship, a method for adding rentals should be present in the Person class. Check out the example in a previous lesson: [Many-to-many relationship]( https://github.com/microverseinc/curriculum-ruby/blob/main/oop/articles/oop_relationships_by_examples.md#many-to-many-relationship) for more information.

2022-09-28 19:28 UTC, medaminedev66 commented on person.rb
> +# p capitalized_trimmed_person.correct_name
[OPTIONAL] It would be nicer to remove the commented code to keep your code clean.

2022-09-28 23:00 UTC, principlebrothers commented on book.rb
> +  end
@medaminedev66, I appreciate time used in reviewing my project. 
From the diagram, the rental is set to private. Which translates,  it can only be read. It applies to all the code you highlighted so kindly check. Below is a diagram for your perusal. 
![Screenshot from 2022-09-28 22-49-03](https://user-images.githubusercontent.com/92553079/192902455-9eb07cf2-63bc-4f17-8f28-ca701bff1cb4.png)
### Example from the clinic example with is implementation
![Screenshot from 2022-09-28 22-54-25](https://user-images.githubusercontent.com/92553079/192902681-d1f242fa-9864-43e3-9d08-adfe53b0a23d.png)
### It's implementation in code
![Screenshot from 2022-09-28 22-56-16](https://user-images.githubusercontent.com/92553079/192902830-e2adbb8c-37c0-4b13-b680-fa03202838a6.png)

2022-09-29 01:09 UTC, Reem-lab approved these changes
# Hi @principlebrothers,👋🏻👋🏻

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉🔥🔥💯💯


<img src="https://media1.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>


## Highlights ✨✨
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Great working on the functionality✅
📌 Good commit messages ✅

## Optional suggestions


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-29 01:12 UTC, principlebrothers commented
@Reem-lab , Thanks for the feedback

2022-09-29 01:12 UTC, merged